import re
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent


class ProtoGencodeFloorTest(unittest.TestCase):
    """The generated protobuf gencode version IS the `protobuf` floor.

    google.protobuf refuses at import time to load gencode NEWER than the
    installed runtime, and the profiler is installed into containers somebody
    else built — commonly with `--no-deps`, so it cannot upgrade what it finds.
    That makes whichever protoc generated signals_pb2.py a user-visible
    dependency, and the two drifting apart is not a packaging nit: it is the
    watcher failing to start, silently, on somebody else's GPU box.

    It has happened once. An unpinned protoc on a developer's PATH stamped
    gencode 7.36.0 while pyproject still claimed a floor it happened to match,
    and the profiler became unimportable in every image shipping protobuf 6.x.
    This test is the thing that was missing.
    """

    def _gencode_version(self):
        source = (REPO_ROOT / 'graphsignal' / 'proto' / 'signals_pb2.py').read_text()
        match = re.search(
            r'ValidateProtobufRuntimeVersion\(\s*'
            r'_runtime_version\.Domain\.\w+,\s*'
            r'(\d+),\s*(\d+),\s*(\d+),',
            source)
        self.assertIsNotNone(
            match,
            'signals_pb2.py carries no version check — it was generated by a '
            'protoc older than 27, which emits none. Regenerate with '
            'scripts/build-protobuf.sh.')
        return int(match.group(1)), int(match.group(2)), int(match.group(3))

    def _declared_floor(self):
        source = (REPO_ROOT / 'pyproject.toml').read_text()
        match = re.search(r'^protobuf\s*=\s*">=(\d+)\.(\d+)"', source, re.MULTILINE)
        self.assertIsNotNone(match, 'no `protobuf = ">=X.Y"` floor in pyproject.toml')
        return int(match.group(1)), int(match.group(2))

    def test_floor_matches_the_generated_gencode(self):
        gen_major, gen_minor, _ = self._gencode_version()
        floor_major, floor_minor = self._declared_floor()

        self.assertEqual(
            (gen_major, gen_minor), (floor_major, floor_minor),
            'signals_pb2.py was generated by protoc stamping gencode '
            f'{gen_major}.{gen_minor}, but pyproject declares protobuf '
            f'>={floor_major}.{floor_minor}. A runtime satisfying that floor '
            'would refuse to load this gencode. Either regenerate with the '
            'pinned protoc in scripts/build-protobuf.sh, or move the floor to '
            'match it — they are one decision, not two.')

    def test_the_generated_module_actually_loads(self):
        # The check above compares strings; this proves the file loads under
        # the protobuf actually installed here.
        from graphsignal.proto import signals_pb2
        self.assertEqual(signals_pb2.Metric.DESCRIPTOR.name, 'Metric')
